# Build settings
markdown: redcarpet
kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
  syntax_highlighter: rouge

redcarpet:
  extensions:
    - fenced_code_blocks
    - autolink
    - no_intra_emphasis
    - with_toc_data
    - html_toc
    - tables

defaults:
  -
    scope:
      path: "doc"
    values:
      layout: doc

# OLD from jekyll 2.x
#highlighter: pygments

# If true, this begins with an existing db
use_db_cache: true
db_cache_filename: _cache/_deploy_cache.db
report_filename: _cache/_deploy_index_report.yaml
report_diff_filename: _cache/_deploy_index_report_diff.yaml
debbuild_release_path: _cache/debbuild_releases
wiki_title_index_filename: _cache/ros_org_wiki_title_index.txt

# If true, this skips finding repos based on the repo sources
skip_discover: false
# If true, this skips updating the known repos
skip_update: false
# If true, this skips scraping the cloned repos
skip_scrape: false
# If true, this skips generating the search index
skip_search_index: false
# Shard count for search index partitioning.
search_index_shards: 20

checkout_threads: 4
checkout_path: _plugins_data/checkout

# if non-empty, only scrape these packages (useful for debugging / partial db updates)
repo_name_whitelist: []
# if non-empty, only scrape these repo ids (useful for debugging / partial db updates)
repo_id_whitelist: []

# domains which are broken
domain_blacklist:
  - 'kforge.ros.org'
  - 'code.in.tum.de'
  #- 'devel.iri.upc.edu'

exclude:
  - _scripts
  - _cache
  - _config
  - _devel
  - _plugins_data
  - _remotes
  - _ruby_libs
  - _sphinx
  - node_modules
  - Gemfile
  - Gemfile.lock
  - README.md
  - Makefile
  - docker

index_old_doc_paths: false

# ROS distros to look for
#
# Distros are given big buttons and "old" distros are relegated to share a
# drop-down list in the distro selector.
#
distros:
  - 'bouncy'
  - 'melodic'
  - 'lunar'
  - 'kinetic'
  - 'indigo'

old_distros:
  - 'ardent'
  - 'jade'
  - 'hydro'

# package list page
packages_per_page: 50
repos_per_page: 50

# uncomment the following line for testing (limit the number of indexed repos)
max_repos: 00

readme_index:
  remove_originals: true

plugins:
  - jekyll-sitemap
  - jekyll-relative-links
