name: Test Build
on: [push, pull_request]

jobs:
  test_build:
    name: Basic CI
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: 'Build Image'
      run: |
        ./docker/build.sh
    - name: 'Run Devel Build'
      run: |
        ./docker/run.sh make test-build